const GITHUB_AUTH_TOKEN = "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"
const BOT_NUMBER = "94766518242"
const SESSION_ID = "PRABATH-MD~0qMEwTxY#jTjjupqlxGsGfN8GCc2q8QaYZ9Dpws4VTnHB_ztwOqI"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
